booklib/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include  # for adding URL from the app's directory
from django.views.generic import RedirectView  # for redirect requests from root URL to app's URL
from django.conf import settings  # for development only
from django.conf.urls.static import static  # for development only

urlpatterns = [
    
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    #path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    #path('', RedirectView.as_view(url='/admin/', permanent=True)),
    #static(settings.STATIC_URL, include('catalog.urls')),
    #static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
]

catalog/urls.py
from django.urls import path
from . import views
from django.conf.urls import url


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^books/$', views.BookListView.as_view(), name='books'),
    url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    url(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    url(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    url(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
]

catalog/models.py
from django.db import models
from django.urls import reverse # для генерации URL
from django.contrib.auth.models import User
import uuid  # для уникальности экземпляров книг
from datetime import date

# Create your models here.
class Genre(models.Model):
    """
    Модель представляет жанр книги
    """
    name = models.CharField(max_length=200, help_text="Введите название жанра (Фантастика, Поэзия)")


    def __str__(self):
        """
        String for represenitng Model object
        """

        return self.name


class Language(models.Model):
    """
    Представление языка книги
    """
    lang = models.CharField(max_length=100)
    lang_ru = models.CharField(max_length=100)
    
    def __str__(self):
        if self.lang == self.lang_ru:
            return '%s' % (self.lang)
        return '%s (%s)' % (self.lang, self.lang_ru)


class Book(models.Model):
    """
    Модель описывает книгу (но не конкретный экземпляр)
    """

    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # ForeignKey потому что какой-то автор эту книгу написал (но мог написать и другие)
    summary = models.TextField(max_length=1000, help_text="Введите краткое описание")
    isbn = models.CharField('ISBN', max_length=13, help_text='13 символов ISBN')
    genre = models.ManyToManyField(Genre, help_text="Выберите жанр для этой книги")
    lang = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    
    

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """
        Возвращает URL для конкретного экземпляра книги
        """
        return reverse('book-detail', args=[str(self.id)])
    
    def display_genre(self):
        """
        Создает строку для отображения жанра
        """
        return ', '.join([genre.name for genre in self.genre.all()[:3]])
        
    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    """
    Представление экземпляра книги
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Уникальный ИД в библиотеке")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'В ремонте'),
        ('o', 'Выдана'),
        ('a', 'Доступна'),
        ('r', 'Зарезервирована'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Доступность книги')
    
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    
    @property
    def is_overdue(self):
        return self.due_back and date.today() > self.due_back


    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned","Set book as returned"),)


    def __str__(self):
        return '%s (%s)' % (self.id, self.book.title)
    
    def display_title(self):
        """
        Создает строку для отображения названия книги
        """
        return self.book.title
        
    display_title.short_description = 'Title'
    
    def display_id(self):
        """
        Создает строку для отображения первых 5 символов id
        """
        return str(self.id)[:5]
        
    display_id.short_description = 'Id'


class Author(models.Model):
    """
    Представление автора
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        """
        Возвращает адрес для доступа к конкретному экземпляру автора
        """
        return reverse('author-detail', args=[str(self.id)])


    def __str__(self):
        return '%s, %s' % (self.last_name, self.first_name)
    
    class Meta:
        ordering = ['last_name']

catalog/views.py
from django.shortcuts import render
from .models import Author, Book, BookInstance, Genre
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin


def index(request):
    """
    Отображение домашней страницы
    """
    # Количество авторово, книг и экземпляров
    num_authors = Author.objects.count()
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    
    # Количество доступных книг
    num_availables = BookInstance.objects.filter(status='a').count()
    
    # Количество жанров
    num_genres = Genre.objects.all().count()
    
    # Количество книг, имеющих в названии слово Джордж
    num_georges_title = Book.objects.filter(title__contains='Джордж').count()
    
    
    # Количество посещений страницы с данного браузера (считается в session)
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    
    # Отрисовка HTML-шаблона index.html
    # данные внутри context
    
    ctx = {
        'num_books': num_books, 
        'num_instances': num_instances, 
        'num_availables': num_availables, 
        'num_authors': num_authors,
        'num_genres': num_genres,
        'num_georges_title': num_georges_title,
        'num_visits': num_visits
    }
    
    return render(
        request,
        'index.html',
        context=ctx
    )



class BookListView(generic.ListView):
    model = Book
    context_object_name = 'book_list'
    # queryset = Book.objects.filter(title__icontains='Джордж')[:2]  # получение двух книг, содержащих 'Джордж' в названии
    queryset = Book.objects.all()
    template_name = 'books/template_name_list.html'  # Нвзвание и расположение шаблона


class BookDetailView(generic.DetailView):
    model = Book


class AuthorListView(generic.ListView):
    model = Author
    context_object_name = 'author_list'
    queryset = Author.objects.all() 
    template_name = 'authors/template_name_list.html'  # Нвзвание и расположение шаблона


class AuthorDetailView(generic.DetailView):
    model = Author

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """
    Generic class-based view список книг, на руках у данного читателя.
    """
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10
    
    def get_queryset(self):
        """
        "o" - код для "on loan", сортировка по дате due_back, сначала старые элементы.
        """
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

catalog/templates/base_templ.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% block title %}<title>Book Library</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <!-- Добавление дополнительного статического CSS файла -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container-fluid">

        <div class="row">
            <div class="col-sm-2">
            {% block sidebar %}
            <ul class="sidebar-nav">
                <li><a href="{% url 'index' %}">Главная</a></li>
                <li><a href="{% url 'books' %}">Книги</a></li>
                <li><a href="{% url 'authors' %}">Авторы</a></li>
                <hr>
                {% if user.is_authenticated %}
                    <li>Пользователь: {{ user.get_username }}</li>
                    <li><a href="{% url 'my-borrowed' %}">Не сданные книги</a></li>
                    <li><a href="{% url 'logout'%}?next={{request.path}}">Выход</a></li>
                {% else %}
                    <li><a href="{% url 'login'%}?next={{request.path}}">Вход</a></li>
                {% endif %}
            </ul>

           {% endblock %}
            </div>
            <div class="col-sm-10 ">
                {% block content %}{% endblock %}
            </div>
        </div>

    </div>

</body>
</html>

catalog/templates/catalog/author_detail.html
{% extends "base_templ.html" %}

{% block content %}
  <h1>Автор: {{ author }}</h1>

  <p><strong>Автор:</strong> <a href="{% url 'author-detail' author.pk %}">{{ author }}</a></p> <!-- author detail link not yet defined -->
    <p><strong>{{ author.first_name }} {{ author.last_name }}</strong></p>
  <p><strong>Родился:</strong> {{ author.date_of_birth }}</p>
  {% if author.date_of_death %}
  <p><strong>Умер:</strong> {{ author.date_of_death }}</p>
  {% endif %}
<div style="margin-left:20px;margin-top:20px">
    <h4>Книги:</h4>
    {% for book in author.book_set.all %}
    <hr>
    <p >{{ book.title }}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_templ.html" %}

{% block content %}
    <h1>Список авторов:</h1>

    {% if author_list %}
    <ul>

      {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author }}</a> 
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>Авторы не найдены</p>
    {% endif %} 
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_templ.html" %}

{% block content %}
  <h1>Книга: {{ book.title }}</h1>

  <p><strong>Автор:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>О книге:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Язык:</strong> {{ book.lang }}</p>
  <p><strong>Жанр:</strong> 
    {% for genre in book.genre.all %} 
        {{ genre }}
        {% if not forloop.last %}, 
        {% endif %}
    {% endfor %}
  </p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Имеющиеся экземпляры:</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Ожидается появление:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Издание:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>№:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_templ.html" %}

{% block content %}
    <h1>Book List</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>Библиотека пуста</p>
    {% endif %} 
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_templ.html" %}

{% block content %}
    <h1>Книги на руках</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>На руках книг нет.</p>
    {% endif %}
{% endblock %}

catalog/templates/index.html
{% extends "base_templ.html" %}
<!-- Переопределение заголовка, установленного в шаблоне -->
{% block title %}<title>HomeBook Library</title>{% endblock %}

{% block content %}
<h1>Домашняя библиотечка</h1>

<p>Добро пожаловать в домашнюю библиотеку. Пробный сайт, разработанный на Django.</p>

<h3>Динамически обновляемое содержимое:</h3>

<p>В библиотеке имеется информация:</p>
<ul>
    <li><b>Книг:</b> {{ num_books }}</li>
    <li><b>Всего экземпляров:</b> {{ num_books }}</li>
    <li><b>Доступных экземпляров:</b> {{ num_availables }}</li>
    <li><b>Авторов:</b> {{ num_authors }}</li>
    
    <li><b>Различных жанров:</b> {{ num_genres }}</li>
    <li><b>Книг, содержащих слово Джордж в названии:</b> {{ num_georges_title }}</li>
</ul>

<p>Вы посетили эту страницу {% if num_visits < 2 %} впервые {% else %} {{ num_visits }} раз {% endif %}</p>

{% endblock %}